version: "3"
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data -port 8070"
    image: "amazon/dynamodb-local:latest"
    container_name: flight-dynamodb-local
    ports:
      - "8070:8070"
    volumes:
      - "./docker:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
